# Generated by Django 5.2.5 on 2025-09-01 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("help_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="help_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="help_requests.helprequest",
            ),
        ),
    ]
