# Generated by Django 5.2.5 on 2025-09-01 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="helper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
