# Generated by Django 5.2.5 on 2025-09-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HelpRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("details", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("shopping", "Shopping"),
                            ("repair", "Repair"),
                            ("childcare", "Childcare"),
                        ],
                        max_length=20,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fulfilled", models.BooleanField(default=False)),
            ],
        ),
    ]
