# Generated by Django 4.2.24 on 2025-09-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="category",
            field=models.CharField(
                choices=[
                    ("shopping", "Einkaufen"),
                    ("tools", "Werkzeugverleih"),
                    ("ride", "Fahrdienst"),
                    ("care", "Pflege"),
                    ("pets", "Haustiere"),
                    ("garden", "Gartenhilfe"),
                    ("plants", "Blumengießen"),
                    ("other", "Sonstiges"),
                ],
                default="other",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
